name: Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent: [random, first]
        seed: [0, 1]
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: |
          python -m pip install -e .[dev]
      - name: Run evaluation
        run: |
          python -m promptgym.evaluation.runner --agent ${{matrix.agent}} --seed ${{matrix.seed}} --outdir runs
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: runs-${{matrix.agent}}-${{matrix.seed}}
          path: runs

